In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.options.display.float_format = '{:,.2f}'.format

### Problema 1
Vamos praticar gerar matrizes e fazer operações com as linhas e colunas:

(a) Crie uma matriz A com as dimensões (5, 4) e elementos aleatórios variando entre 0 e 50, com o 50 incluso;

__Dica:__ Utilize as funções `np.random.randint` e `np.reshape`

(b) Retorne a média do vetor

(c) Retorne os menores valores de cada coluna;

(d) Retorne os maiores valores de cada linha.

Resposta A

In [3]:
matriz_A = np.random.randint(0,51, size=20)
matriz_A = matriz_A.reshape(5,4)
matriz_A

array([[35, 37,  6,  5],
       [39, 12, 12, 47],
       [19, 10, 35, 22],
       [13, 46,  4, 32],
       [ 9, 25, 48, 23]])

Resposta B

In [4]:
matriz_A.mean()

23.95

Resposta C

In [6]:
print(matriz_A)
matriz_A.min(axis=0)

[[35 37  6  5]
 [39 12 12 47]
 [19 10 35 22]
 [13 46  4 32]
 [ 9 25 48 23]]


array([ 9, 10,  4,  5])

In [8]:
print(matriz_A)
matriz_A.max(axis=1)

[[35 37  6  5]
 [39 12 12 47]
 [19 10 35 22]
 [13 46  4 32]
 [ 9 25 48 23]]


array([37, 47, 35, 46, 48])

### Problema 2

Crie um objeto DataFrame que contenha os dados da tabela abaixo, os quais se referem ao peso, altura e idade de cinco pessoas:


| Peso (kg) | Altura (cm) | Idade (anos) |
|-----------|-------------|--------------|
|  47 | 161	| 31 |
|  80 | 170	| 21 |
|  60 | 175	| 16 |
|  90 | 162	| 28 |
| 100 | 185	| 23 |
| 147 | 189 | 32 |

Com base no DataFrame criado, realize o que for pedido nos itens abaixo:

(a) Visualize apenas os dados da coluna que contém a altura das pessoas;

(b) Obtenha a idade média das pessoas;

(c) Obtenha os dados das pessoas que estão abaixo da altura média;

(d) Crie um nova coluna no DataFrame que contenha o IMC (Índice de Massa Corporal) de cada pessoa;

__Obs.:__ A fórmula para o IMC é dada por IMC = Peso/(Altura)² com o peso em kg e a altura em metros.

(e) Remova a coluna que contém a idade das pessoas;

(f) Crie uma nova coluna chamada Classificação, que contenha a classificação de cada indivíduo, de acordo com o seu IMC. Para isso, consulte a tabela abaixo.

| IMC             | Classificação |
|-----------------|---------------|
Menor que 18,5    | Subpeso |
Entre 18,5 e 24,9 | Normal |
Entre 25,0 e 29,9 | Sobrepeso |
Entre 30,0 e 39,9 | Obesidade Grau I |
Maior que 40,0    | Obesidade Grau II |

(g) Salve esses dados do DataFrame em um arquivo csv.

Resposta A

In [11]:
df = pd.read_clipboard()
df

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
2         60          175            16
3         90          162            28
4        100          185            23
5        147          189            32

In [17]:
df[['Altura (cm)']]

Altura (cm)
0          161
1          170
2          175
3          162
4          185
5          189

In [ ]:
Resposta B

In [20]:
df['Idade (anos)'].mean()

25.166666666666668

Resposta C

In [24]:
altura_media = df['Altura (cm)'].mean()
df[df['Altura (cm)'] < altura_media]

Peso (kg)  Altura (cm)  Idade (anos)
0         47          161            31
1         80          170            21
3         90          162            28

In [ ]:
Resposta D

In [27]:
df['IMC'] = df['Peso (kg)']/((df['Altura (cm)']/100)**2)
df

Peso (kg)  Altura (cm)  Idade (anos)   IMC
0         47          161            31 18.13
1         80          170            21 27.68
2         60          175            16 19.59
3         90          162            28 34.29
4        100          185            23 29.22
5        147          189            32 41.15

In [ ]:
Resposta E

In [29]:
df.drop(['Idade (anos)'], axis = 1)
df

Peso (kg)  Altura (cm)  Idade (anos)   IMC
0         47          161            31 18.13
1         80          170            21 27.68
2         60          175            16 19.59
3         90          162            28 34.29
4        100          185            23 29.22
5        147          189            32 41.15

In [ ]:
Resposta F

In [32]:
df_1 = pd.read_clipboard()
df_1

IMC      Classificação
0     Menor que 18,5            Subpeso
1  Entre 18,5 e 24,9             Normal
2  Entre 25,0 e 29,9          Sobrepeso
3  Entre 30,0 e 39,9   Obesidade Grau I
4     Maior que 40,0  Obesidade Grau II

In [34]:
#df['Classificação'] = df.merge(df_1[['Classificação']], how="outer", on="IMC")
import sys

df['Classificação']=pd.cut(df['IMC'], bins=[0, 18.5, 24.9, 29.9, 39.9, sys.maxsize], labels=['Subpeso', 'Normal', 'Sobrepeso', 'Obesidade Grau I', 'Obesidade Grau II'])
display(df)

Peso (kg)  Altura (cm)  Idade (anos)   IMC      Classificação
0         47          161            31 18.13            Subpeso
1         80          170            21 27.68          Sobrepeso
2         60          175            16 19.59             Normal
3         90          162            28 34.29   Obesidade Grau I
4        100          185            23 29.22          Sobrepeso
5        147          189            32 41.15  Obesidade Grau II

### Problema 3

O arquivo avocado.xlsx consiste em um dataset que contém dados sobre vendas de abacates  em diversas regiões dos Estados Unidos. Essa dataset contém as seguintes colunas:

| Coluna | Descrição |
|--------|-----------|
| Date | data da observação |
| AveragePrice | preço médio de um único abacate |
| year | ano |
| region | cidade ou região da observação |
| Total Volume | volume total de abacates vendidos |

Além das informações acima, contidas no arquivo avocado.xlsx, o tipo do abacate (convencional ou orgânico) também seria uma informação importante para a sua análise. Suponhamos que você conseguiu essas informações para cada uma das observações do arquivo avocado.csv, na mesma ordem, e salvou-as no arquivo avocado_type.xlsx. Portanto, tudo o que você precisa é juntar esses dois arquivos em um mesmo DataFrame.

Com o DataFrame criado, obtenha o que é solicitado nos itens elencados abaixo:




In [57]:
df_avocado = pd.read_csv("data/avocado.csv", sep = ';')
df_type = pd.read_excel("data/avocado_type.xlsx")

df_concat = pd.concat([df_avocado, df_type], axis=1, join="inner")
df_concat.to_csv('Avocado_completa.csv', index = False)
df_concat

Date  AveragePrice  Total Volume  year            region  \
0      2015-12-27          1.33     64,236.62  2015            Albany   
1      2015-12-20          1.35     54,876.98  2015            Albany   
2      2015-12-13          0.93    118,220.22  2015            Albany   
3      2015-12-06          1.08     78,992.15  2015            Albany   
4      2015-11-29          1.28     51,039.60  2015            Albany   
...           ...           ...           ...   ...               ...   
18244  2018-02-04          1.63     17,074.83  2018  WestTexNewMexico   
18245  2018-01-28          1.71     13,888.04  2018  WestTexNewMexico   
18246  2018-01-21          1.87     13,766.76  2018  WestTexNewMexico   
18247  2018-01-14          1.93     16,205.22  2018  WestTexNewMexico   
18248  2018-01-07          1.62     17,489.58  2018  WestTexNewMexico   

               type  
0          orgânico  
1      convencional  
2      convencional  
3          orgânico  
4          orgânico  
...             ...  
18244  convencional  
18245  convencional  
18246  convencional  
18247  convencional  
18248  convencional  

[18249 rows x 6 columns]

(a) A quantidade de abacates do tipo convecional e do tipo orgânico.

In [74]:
df_concat['type'].value_counts()


orgânico        9135
convencional    9114
Name: type, dtype: int64


(b) A quantidade de registros (linhas) de abacates vendidos para cada região ordenada da maior venda para a menor.

In [ ]:
d

(c) Para que todos os labels das colunas fiquem padronizados, renomeie aqueles que estão iniciando em letra minúscula para que iniciem em letra maiúscula, trocando espaço por _ e adicionando _ como separação de texto.

In [78]:
df_concat.columns

Index(['Date', 'AveragePrice', 'Total Volume', 'year', 'region', 'type'], dtype='object')

(d) Essa dado possui duplicados? Se sim, remova-os do dataset.

In [75]:
df_concat.duplicated().sum()

0

(e) Retire dos dados a região 'TotalUS'

In [95]:
#df_concat[df_concat['region'] == 'TotalUS']
df_concat.drop(df_concat[df_concat['region'] == 'TotalUS'], axis = 0) 

#df_concat

KeyError: "['Date' 'AveragePrice' 'Total Volume' 'year' 'region' 'type'] not found in axis"

(g) Apresente as regiões que mais venderam abacate em todo o período em ordem decrescente.

In [112]:
df_concat.groupby(['region'])['Total Volume'].sum().sort_values(axis = 0, ascending = False)

region
TotalUS               5,864,740,181.80
West                  1,086,779,155.75
California            1,028,981,653.17
SouthCentral          1,011,279,618.83
Northeast               713,280,909.56
Southeast               615,238,409.11
GreatLakes              589,642,549.29
Midsouth                508,349,357.20
LosAngeles              507,896,547.63
Plains                  311,188,529.11
NewYork                 240,734,127.53
DallasFtWorth           208,419,286.55
Houston                 203,167,867.80
PhoenixTucson           195,643,312.50
WestTexNewMexico        144,521,839.78
Denver                  138,902,535.99
SanFrancisco            135,830,191.78
BaltimoreWashington     134,713,919.32
Chicago                 133,702,338.51
Portland                110,552,211.60
Seattle                 109,214,177.96
MiamiFtLauderdale        97,673,224.03
Boston                   97,273,984.83
SanDiego                 89,791,919.69
Atlanta                  88,605,118.85
Sacramento        

(h) Calcule o volume total de abacates vendidos para cada tipo e ano.

In [113]:
pd.DataFrame(df_concat.groupby(['type', 'year'])['Total Volume'].sum())

Total Volume
type         year                 
convencional 2015 2,262,212,670.62
             2016 2,537,092,185.32
             2017 2,387,148,981.92
             2018   753,606,839.89
orgânico     2015 2,123,255,991.42
             2016 2,283,797,706.51
             2017 2,547,156,717.35
             2018   629,131,500.37

(f) existe alguma região que foi a maior responsável pela queda na produção de 2018?

In [147]:
pd.DataFrame(df_concat.groupby(['region', df_concat['year']])['Total Volume'].sum()) - df_concat['Total Volume']

Total Volume   0   1   2   3   4   5   6   7   8  ...  \
region           year                                                    ...   
Albany           2015           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2016           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2017           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2018           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
Atlanta          2015           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
...                             ...  ..  ..  ..  ..  ..  ..  ..  ..  ..  ...   
West             2018           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
WestTexNewMexico 2015           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2016           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2017           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   
                 2018           NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN  ...   

                       18239  18240  18241  18242  18243  18244  18245  18246  \
region           year                                                           
Albany           2015    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2016    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2017    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2018    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
Atlanta          2015    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
...                      ...    ...    ...    ...    ...    ...    ...    ...   
West             2018    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
WestTexNewMexico 2015    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2016    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2017    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   
                 2018    NaN    NaN    NaN    NaN    NaN    NaN    NaN    NaN   

                       18247  18248  
region           year                
Albany           2015    NaN    NaN  
                 2016    NaN    NaN  
                 2017    NaN    NaN  
                 2018    NaN    NaN  
Atlanta          2015    NaN    NaN  
...                      ...    ...  
West             2018    NaN    NaN  
WestTexNewMexico 2015    NaN    NaN  
                 2016    NaN    NaN  
                 2017    NaN    NaN  
                 2018    NaN    NaN  

[216 rows x 18250 columns]

In [150]:
df_concat.groupby(['region', 'AveragePrice'])['Total Volume'].sum()

region            AveragePrice
Albany            0.85            81,694.23
                  0.93           118,220.22
                  0.98           109,428.33
                  0.99           367,980.46
                  1.02           167,610.50
                                    ...    
WestTexNewMexico  2.50            16,137.93
                  2.57             5,647.48
                  2.79             5,562.00
                  2.83             4,984.76
                  2.93             5,373.88
Name: Total Volume, Length: 6359, dtype: float64

(g) Qual cidade menos faturou com a venda de abacates?

### Problema 4

Com base no dataset 'Video_Games_Sales.csv' responda:



(a) Quantos jogos existem em cada genero?


(b) Temos duplicados nesses dados? E nulos?

(b) Quantos jogos de cada publisher receberam nota acima de 9 na avaliação dos usuarios?


(c) Faça uma tabela que mostre o total vendido por ano por pais/globalmente de cada publisher? Você consegue observar algum padrão? Com se comportaram as vendas na América do Norte (NA) ao longo do tempo? O mesmo foi visto nos demais lugares? 



(d) Qual foi jogo mais vendido na união européia? De que ano ele é e qual a editora?



(e) Quantos % os generos ['Racing', 'Sports', 'Shooter'] representam na base de dados? 

(f) Qual plataforma vendeu menos globalmente? obs: imprimir somente o nome

### Problema 5
A pasta 'data/datasus' contém informações sobre casos de dengue e tabelas auxiliares. <br>

| Tabela | Conteúdo |
|--------|----------|
| Dengue | Quantidade de casos por município |
| Agua | Quantidade de residências em cada município por tipo o abastecimento de água |
| InstalacoesSanitarias | Quantidade de residências em cada município por tipo de rede de esgoto |
| Pib | PIB per capita de cada município |
| Municipios | Relaciona o id_municipio com seu nome e estado |
| Populacao | Quantidade de pessoas morando em áreas urbanas, rurais e população total por município |
| Sexo | Quantidade de pessoas por sexo em cada município |

(a) Calcular o número de casos de dengue por cada estado apresentando os dados em ordem decrescente.


(b) Utilizando o dataset InstalacoesSanitarias.csv, determine o número de pessoas que não possuem meio sanitário algum de descarte de dejetos por estado.

(c) Crie uma coluna com a posição de ranking considerando o PIB. Os maiores PIB devem ter os menores valores de ranking.

(d) Qual o PIB dos 5 municípios com mais casos de dengue e sua posição no ranking?