In [1]:
import numpy as np

In [2]:
np.arange(5, 20, 2)

array([ 5,  7,  9, 11, 13, 15, 17, 19])

In [42]:
np.random.rand(4, 3)

array([[0.13931457, 0.08731955, 0.78800206],
       [0.32615094, 0.54106782, 0.24023518],
       [0.54542293, 0.4005545 , 0.71519189],
       [0.83667994, 0.58848114, 0.29615456]])

In [146]:
#np.random.seed(44)
np.random.randint(0, 500,(18, 13))

array([[ 40, 307, 471,  19, 446,  63, 118, 252,  10,  82, 195, 381, 121],
       [266, 219, 435,  11, 126, 358, 326, 422, 363, 391, 405, 108, 138],
       [ 53, 321, 405, 425,  80, 353, 455,  33, 448, 185, 359, 394, 494],
       [ 38,  40,  82,   1, 484, 164, 100, 207, 384, 409, 119, 372, 324],
       [497,  44, 228,  62,   4, 463, 244, 194, 132,  30, 155, 497, 413],
       [157, 483, 429, 289, 343,  50, 375,  80, 237, 122, 361, 398, 295],
       [446, 329, 433, 288,  80, 450,  63, 380, 123, 378, 238,  13, 158],
       [371,  42,  84, 488, 375,   3, 384, 395, 113, 391,  27, 294, 323],
       [ 87, 263, 176,  78,  99,  42, 428, 184, 126, 221, 416, 272, 108],
       [ 99, 165, 143,  38, 143, 414, 151, 170, 163, 111, 171, 155,   6],
       [259,  37, 233, 147, 437, 342, 488, 304, 272,  78, 152,   3, 437],
       [285,  83, 110, 481, 390, 345, 462, 282, 237, 106, 171, 103, 283],
       [369, 493, 318, 487,  80, 467,  65, 196,  26, 332,  60, 386, 253],
       [262, 269, 214, 314, 363,  11, 